const express = require('express');
const {
    getOperatorDashboard,
    getOperatorBills,
    receivePayment,
    getOperatorPayments,
    getOperatorConsumers,
    getOperatorConsumerById,
    getOperatorComplaints,
    updateOperatorComplaint,
} = require('../controllers/operator.controller');
const { protect, authorize } = require('../middleware/auth.middleware');

const router = express.Router();

// All routes require OPERATOR role (or ADMIN for testing)
const operatorAuth = [protect, authorize('OPERATOR', 'ADMIN')];

router.get('/test', (req, res) => res.json({ message: 'Operator routes are active!' }));

// ── Dashboard ──────────────────────────────────────────────────
// GET /api/operator/dashboard
router.get('/dashboard', ...operatorAuth, getOperatorDashboard);

// ── Bills ───────────────────────────────────────────────────────
// GET /api/operator/bills   (bills generated by this operator)
router.get('/bills', ...operatorAuth, getOperatorBills);

// ── Payments ────────────────────────────────────────────────────
// GET /api/operator/payments        (list all payments)
router.get('/payments', ...operatorAuth, getOperatorPayments);

// POST /api/operator/payments/receive  (record cash/offline payment)
router.post('/payments/receive', ...operatorAuth, receivePayment);

// ── Consumers ───────────────────────────────────────────────────
// GET /api/operator/consumers         (list + search)
router.get('/consumers', ...operatorAuth, getOperatorConsumers);

// GET /api/operator/consumers/:id     (single consumer detail)
router.get('/consumers/:id', ...operatorAuth, getOperatorConsumerById);

// ── Complaints ──────────────────────────────────────────────────
// GET /api/operator/complaints        (list)
router.get('/complaints', ...operatorAuth, getOperatorComplaints);

// PATCH /api/operator/complaints/:id  (update status)
router.patch('/complaints/:id', ...operatorAuth, updateOperatorComplaint);

module.exports = router;
